### ISSUE TITLE
License file is missing in the npm package

### ISSUE THREAD

**Issue by mortymacs** [joe-re/sql-language-server#163]
Hi,

I'm maintaining the AUR package. The last release doesn't contain LICENSE file in the npm package. Do you have any plan to bring it back or it's somewhere else?

Cheers,
Mort

**Comment by joe-re** [comment]
@mortymacs HI, thanks for your suggestion. I'll make it contain the LICENSE file from the next release. Thanks.

**Comment by mortymacs** [comment]
Thank you!
So, in this version (1.13.0) I'll remove the license file and in the next version I'll add it.

**Comment by joe-re** [comment]
@mortymacs Hi. We've released v1.3.1 and now it has the LICENSE file here. https://www.npmjs.com/package/sql-language-server?activeTab=explore
Thanks. 🙏

**Comment by mortymacs** [comment]
Thank you!
I ignored version 1.3.0 and updated the package directly to the latest version (1.3.1).
