### ISSUE TITLE
support DROP Table

### ISSUE THREAD

**Issue by joe-re** [joe-re/sql-language-server#172]
ref #129

**Comment by ravilock** [comment]
I'd like to contribute with this issue. I already made a fork.
Are you guys open to contributions?

**Comment by ravilock** [comment]
What do you think?

**Comment by joe-re** [comment]
@ravilock Thanks! I'll look at your PR. 👍

**Comment by joe-re** [comment]
Now we support DROP Table statement from v1.7.0. 🎉 
Thanks @ravilock for your great work! 🙏
