### ISSUE TITLE
Is v1.5.1 the latest release?

### ISSUE THREAD

**Issue by p-linnane** [joe-re/sql-language-server#189]
Hello 👋 . I'm a maintainer for the [Homebrew](https://brew.sh) project. While packaging v1.5.1 of sql-language-server we noticed that it is not marked as the latest release on GitHub. I wanted to check if this was an oversight, since we usually only package releases marked as latest. Thanks!

Relates to https://github.com/Homebrew/homebrew-core/pull/128893

**Comment by joe-re** [comment]
@p-linnane Hi, sorry I seem to forget to tag it as the latest. I re-tagged it now, thanks. 🙏

**Comment by p-linnane** [comment]
No worries, thank you!
