### ISSUE TITLE
root dir not find . with neovim LSP

### ISSUE THREAD

**Issue by Keeyuu** [joe-re/sql-language-server#192]
It's not working
:lspInfo 
get a error ->  root directory:    Not found.
<img width="1357" alt="image" src="https://user-images.githubusercontent.com/38851875/236169449-5f560f7d-76ff-48a4-a2f5-65c4b7741797.png">

**Comment by williamboman** [comment]
This is not the right place to file the issue. sqlls in nvim-lspconfig currently relies on the existence of a `.sqllsrc.json` file in your project in order to start.

**Comment by Keeyuu** [comment]
> This is not the right place to file the issue. sqlls in nvim-lspconfig currently relies on the existence of a `.sqllsrc.json` file in your project in order to start.

Thank you very much for your reply. Just installing sqlls alone will not be enough to run it, correct? It seems that I also need to install a plug-in.

**Comment by williamboman** [comment]
No, you need to provide a [configuration file](https://github.com/joe-re/sql-language-server#configuration). The [default server configuration in nvim-lspconfig](https://github.com/neovim/nvim-lspconfig/blob/master/lua/lspconfig/server_configurations/sqlls.lua) is currently configured to only start the server if it finds a `.sqllsrc.json` file.

**Comment by cruzluna** [comment]
Thanks @williamboman  for the comment. Got my sqlls working. 

Here is a sample .sqllrc.json I threw into my repo: 
```json
{
  "adapter": "postgres",
  "host": "localhost",
  "port": 3306,
  "user": "username",
  "password": "password",
  "database": "mysql-development"
}
```

For more guidance: [docs](https://github.com/joe-re/sql-language-server#configuration)
