### ISSUE TITLE
 Error message: Expected [.], [A-Za-z0-9_:[\]'], or [A-Za-z0-9_] but " " found.

### ISSUE THREAD

**Issue by longmenzhitong** [joe-re/sql-language-server#201]
My sql and the error message which bothers me:
<img width="1029" alt="image" src="https://github.com/joe-re/sql-language-server/assets/101724143/da50cab1-1666-4661-9617-84dfa5a8aae8">
My neovim lspconfig:
<img width="595" alt="image" src="https://github.com/joe-re/sql-language-server/assets/101724143/fe529d82-2bde-4838-8182-7d0e3e52da6c">
And my sqllsrc.json:
<img width="227" alt="image" src="https://github.com/joe-re/sql-language-server/assets/101724143/6031cdc9-ae23-4ad3-ba98-c108c3896c20">
Why the wrong error message appears? How can I fix it? Please help!

**Comment by AsgrimS** [comment]
Having the same issue, can't get it to work inside neovim at all

**Comment by joe-re** [comment]
@longmenzhitong @AsgrimS Thanks for your report. We fixed the issue you reported and released it.
Please check it with the latest version of sql-language-server. Thanks 🙏
