### ISSUE TITLE
The package `@joe-re/sql-parser` is not up to date with the code in this repo

### ISSUE THREAD

**Issue by widcardw** [joe-re/sql-language-server#203]
Hello, I'd like to use the package `@joe-re/sql-parser`, and I can install it from npmjs.com. However, the package on npm does not contain the method `parseAll`.

Here's the link: https://www.npmjs.com/package/@joe-re/sql-parser/v/1.5.1?activeTab=code

<img width="930" alt="image" src="https://github.com/joe-re/sql-language-server/assets/55699713/6217dc8a-705a-4acd-a9de-4334b56b83a4">

However, the code in this repo is up to date. Maybe there's some mistakes, and it failed to build this package separately, so the old version was uploaded...

Please take a look and fix this problem, thank you!

**Comment by joe-re** [comment]
@widcardw Hi, thanks for your report. We released v1.5.2 and it includes parseAll. Thanks. 🙏 
https://www.npmjs.com/package/@joe-re/sql-parser/v/1.5.2?activeTab=code
