### ISSUE TITLE
add support for drop view

### ISSUE THREAD

**Issue by luccahuguet** [joe-re/sql-language-server#244]
currently is says: `Expected "--", "/*", "TYPE", or [ \t\n\r] but "v" found.`

**Comment by joe-re** [comment]
@luccahuguet HI, thanks for your report.
We've released v1.7.1 and now we support drop view statement.
Please check it, thanks.

**Comment by luccahuguet** [comment]
> @luccahuguet HI, thanks for your report.
> We've released v1.7.1 and now we support drop view statement.
> Please check it, thanks.

This is awesome. Thank you
