### ISSUE TITLE
support CTE

### ISSUE THREAD

**Issue by joe-re** [joe-re/sql-language-server#51]
refer: https://about.gitlab.com/handbook/business-ops/data-team/platform/sql-style-guide/#use-ctes-common-table-expressions-not-subqueries

**Comment by forivall** [comment]
Also see [postgres docs](https://www.postgresql.org/docs/9.6/queries-with.html) - they're also known as "with" expressions (as that's what i searched for). I was hoping to have "go to definition" for the aliases in a CTE, alas, not yet supported here.

**Comment by joe-re** [comment]
fixed by #181
