### ISSUE TITLE
Support coc.nvim

### ISSUE THREAD

**Issue by joe-re** [joe-re/sql-language-server#61]
https://github.com/neoclide/coc.nvim

#59

**Comment by love4myxsg** [comment]
Can we have a full example in <coc-settings.json>
It seems new lint rules is not effective with following settings:
(a)
"sql": {
"command": "sql-language-server",
"args" : ["up", "--method", "stdio"],
"filetypes": ["sql", "mysql"],
"rules": {
"reserved-word-case": ["error", "lower"],
"linebreak-after-clause-keyword": "off"
}

(b)
"sql": {
"command": "sql-language-server",
"args" : ["up", "--method", "stdio"],
"filetypes": ["sql", "mysql"]
"connections": [
{
"name": "sqlite3",
"adapter": "sqlite3",
"filename": "/tmp/test.sqlite3",
"projectPaths": ["/tmp"],
"rules": {
"reserved-word-case": ["error", "lower"],
"linebreak-after-clause-keyword": "off"
}
}
]
}

Besides, connections not working too.

**Comment by love4myxsg** [comment]
Appreciate for your hardworking.
and Sqlite3 support is a fantastic idea!
One senarios I can image:
  (a)Firstly, export any DB's struture into Sqlite3,  
  (b)Then, connect to local Sqlite3,  and completion works for any "SQL" programming with incredible speed,
  maybe better than SQL developer itself (due to slow connection with remote server)
  , am I right?
But, I can not make sqlite3 connection works now,
  need more help with "coc-settings.json" here.
  Thanks very much.

**Comment by joe-re** [comment]
@love4myxsg Hi, thank you for your feedback.

> One senarios I can image:
(a)Firstly, export any DB's struture into Sqlite3,
(b)Then, connect to local Sqlite3, and completion works for any "SQL" programming with incredible speed,
maybe better than SQL developer itself (due to slow connection with remote server)
, am I right?

I think that should depend on developers.
Actually I've not heard about that usage yet, but it's possible. (And probably it's useful for some developers environment?)

If you have any ideas that sql-language-server can support, please let us know freely!
Currently I'm working on implementing support coc settings(workspace/configuration). Please gimme a little time. 🙏

**Comment by love4myxsg** [comment]
FYI:
  following coc setting is working curretnly:
    "sql": {
      "command": "sql-language-server",
      "args" : ["up", "--method", "stdio"],
      "filetypes": ["sql", "mysql"],
    }

  only support default lint support.
  not support others like connections to DB and completion.

**Comment by joe-re** [comment]
@love4myxsg We released v0.12.0 which supports workspace/configuration.
Please refer [this](https://github.com/joe-re/sql-language-server#example-of-workspace-configuration) to get to know how to use it.
If you find something wrong tell us freely, thanks.
