### ISSUE TITLE
'A linebreak is required...' lint error incorrectly showing with nvim lsp

### ISSUE THREAD

**Issue by nkhlmn** [joe-re/sql-language-server#64]
Using this with nightly neovim and the completion-nvim plugin. I get this lint error for every keyword regardless of whether there is a new line or not.

<img width="483" alt="Screen Shot 2020-09-30 at 6 54 17 PM" src="https://user-images.githubusercontent.com/34255347/94757251-8d6d1200-034e-11eb-8555-75233eaff5ce.png">

I have the following in my init.vim:

```
lua <<EOF

local nvim_lsp = require'nvim_lsp'

local on_attach = function(client)
    require'completion'.on_attach(client)
    require'diagnostic'.on_attach(client)
end

nvim_lsp.sqlls.setup({ on_attach=on_attach })

EOF



let g:LanguageClient_serverCommands = {
    \ 'sql': ['sql-language-server', 'up', '--method', 'stdio'],
    \ }
```

**Comment by joe-re** [comment]
@nkhlmn Thanks for your report. I'll deal with it.

**Comment by joe-re** [comment]
@nkhlmn Hi, I just tested it with my Neovim environment and seems it works to me.
My settings are here.

```
lua <<EOF
require'nvim_lsp'.sqlls.setup{
  cmd = {"sql-language-server", "up", "--method", "stdio"};
}
EOF
```

When you reopen or write a file, that error state does not rerender?

**Comment by Iron-E** [comment]
I am using the same config you show above, but I get this:

![cap](https://user-images.githubusercontent.com/36409591/135530969-3ee370a7-5a3c-4577-9aa6-2a226d57cfe8.png)

**Comment by joe-re** [comment]
Hi, thanks for your report.
May I know SQL that you're trying to?

2021年10月1日(金) 6:13 Iron-E ***@***.***>:

**Comment by joe-re** [comment]
@Iron-E 
Hi, thanks for your report.
May I know SQL that you're trying to?

**Comment by Iron-E** [comment]
Thanks for the fast response! It happens for MySQL and PgSQL as well as Oracle (but I don't know if you support that onel.

**Comment by joe-re** [comment]
@Iron-E Sorry, I meant your SQL example that is failed to parse.(Because your error is not a DB connection error but the parser failed to parse it.)
Since it's not a connection error, no matter for DB vendor.
Thanks.

**Comment by Iron-E** [comment]
Ah, gotcha. In that case, here's an example PgSQL snippet that reproduces it for me:

```pgsql
CREATE TABLE IF NOT EXISTS location (
  id bigint GENERATED ALWAYS AS ID
);
```

I have to double check but I think even `CREATE TABLE location ();` does it as well.

Related to #63 and #67?

**Comment by joe-re** [comment]
@Iron-E Sorry for my late reply. Yes, you're right.
Right now I'm working on dealing with CREATE TABLE statement #91.
Please give us more a little time to release, thanks.

**Comment by joe-re** [comment]
@Iron-E Hi, we've released new feature to support CREATE TABLE statement by 1.2.0. Please check this out!.
If you see any wrong please let us know, thanks. 🙏
