### ISSUE TITLE
npm sqlint package misleads to sql-language-server repo

### ISSUE THREAD

**Issue by Doc999tor** [joe-re/sql-language-server#66]
`npm i -g sqlint` installs `sqlint` cli package which is not related (as far as I can see) to `sql-language-server`
If it does, pls check what is going on there (the package fails to parse simple sql code)

https://www.npmjs.com/package/sqlint

**Comment by joe-re** [comment]
@Doc999tor sqlint is a part of sql-language-server module, which is for linting.
sqlint itself is providing cli IF for only linting.
For the part of failing case that you've mentioned, please share us simple example and if you can see anyerrors, please share it us also.
I'll mark this as complete, if you have any problems please feel free to create a new issue, thanks.
