### ISSUE TITLE
Add BigQuery to supported DBs?

### ISSUE THREAD

**Issue by HalfMillennium** [joe-re/sql-language-server#68]
Has anyone thought about extending this language server to support BigQuery as well?

I've looking into how I might develop a language server for BQ, and I stumbled upon this repo. Would it be simpler to develop my own from scratch or simply extend this one?

**Comment by joe-re** [comment]
@HalfMillennium Hi, thanks for asking. I understand BigQuery has its own UI to execute queries though, may I know your use-case? Thanks.
