### ISSUE TITLE
Unable to change configuration when using JupyterLab

### ISSUE THREAD

**Issue by cccs-jc** [joe-re/sql-language-server#69]
I've installed sql-language-server and I'm able to use it both in VSCode and in JupyterLab.

In both environment I'm able to see the diagnostic errors and the completion of keywords such as SELECT, FROM, WHERE.

However in JupyterLab I'm not able or don't know how to configure sql-language-server to connect to a sqlite3 sample database in order to benefit from the completion of the table/column names.

Is there a way to do this? I've tried putting configuration inside the jupyterlab advanced settings @krassowski/jupyterlab-lsp:plugin. I've also tried inside ~/.config but no luck..

**Comment by joe-re** [comment]
Hi, @cccs-jc .
Thanks for asking this. It's very interesting.
Unfortunately I'm not familiar with JupyterLab, I need time to figure how it does.
I'll try it when I have time though, if you have any further information, please share us, thanks.

**Comment by cccs-jc** [comment]
hey @joe-re 
I have figured it out. Turned out to be small fixes after all. I'll make a PR.

I've also added many features which I would love to contribute back. I'll crete another issue to discuss this. Sounds good?

**Comment by joe-re** [comment]
@cccs-jc Hi, of course! It's always welcome!
