### ISSUE TITLE
Unable to configure development environment

### ISSUE THREAD

**Issue by HalfMillennium** [joe-re/sql-language-server#70]
For the past few days, I've been trying to get a development environment up and running on my local machine, but I can't quite seem to get it working. After cloning the repo, and ensuring that Docker is properly installed, I receive the following error.

```
ssets_1    | /bin/sh: 1: run-p: not found
assets_1    | error Command failed with exit code 127.
assets_1    | info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

I then tried installing run-p with `npm install run-p`, but this only leads my down an endless rabbit hole of installing npm packages, and `npm install` doesn't help. Eventually, I receive issues with the `webpack.config.js` file included in the example, so I assume this is happening because of a bit of setup that I'm missing?

**Comment by joe-re** [comment]
@HalfMillennium Hi, thanks for raising it.
I've updated dependencies, can you try with the latest release branch?
If it doesn't work, can you try to `yarn install` on your local machine, then `docker-compose up` again?
