### ISSUE TITLE
Help!

### ISSUE THREAD

**Issue by yangdengcheng** [joe-re/sql-language-server#71]
How to fix this problem??!!

![image](https://user-images.githubusercontent.com/33214847/127317005-2e970fdd-3650-4269-94da-aa7a5d90ceb0.png)

**Comment by joe-re** [comment]
@yangdengcheng Hi, thank you for raising the issue.
Currently, I'm working on trying to identify the problem.
If you can share with us something reproducible example repo, that would be really helpful for us. Thanks.

**Comment by joe-re** [comment]
@yangdengcheng Hi, I've updated dependencies and dev scripts. Can you try it with the latest release branch? Thanks.
