### ISSUE TITLE
Proposal to support json adapter

### ISSUE THREAD

**Issue by cccs-jc** [joe-re/sql-language-server#75]
sql-language-server currently supports 3 types of adapters

- MySQL
- PostgreSQL
- SQLite3

In this fork I have implemented a forth `adapter` named `json`. The idea is to load a schema from an external file. For platform like spark this is very useful because users can create tables in their own spark environment. Also it is difficult to configure the spark driver in sql-language-server the same way it's configured in the user's jupyterlab notebooks.

@joe-re Have a look at the following documentation. If you like the idea of an external `json` adapter and the integration with JupyterLab I will spend more time on these features and make proper PR to your repository. I believe it would best for the community to incorporate this work into your code base.

https://github.com/cccs-jc/sql-language-server/tree/develop/example/jupyterlab

Let me know what you think. Looking forward to collaborate.
Cheers
jc

**Comment by joe-re** [comment]
@cccs-jc Hi, thanks for raising this discussion and sharing your idea!
I've looked through it and, felt that's so cool!
Actually, adding something adapter to read schema information from a file is that I've also thought it before, so direction is completely no prob to me.
Please go ahead and if I can help something, please feel free to ask me, thanks!
