### ISSUE TITLE
Issue with running Monaco example with docker connection

### ISSUE THREAD

**Issue by jasminediaconu** [joe-re/sql-language-server#84]
Hey, I was trying to run both the monaco example and docker to have the db connection but I don't seem to get it work.
I tried to run: 
1. `yarn install`
2. `docker-compose up`
3. `yarn && yarn dev`

And also:
1. `yarn install`
2. `yarn && yarn dev`
3. `docker-compose up`

However I see both docker and the editor are trying to connect to port 3000 and that gives me an error. I tried to change the port number but when I do, it doesn't show up the databases on monaco.

I also tried to just run `docker-compose up` and connect to localhost:3000 but the page doesn't load.

Is there any step that I am missing?

**Comment by joe-re** [comment]
@jasminediaconu HI, thanks for your report. Is there any error on localhost:3000? Is it 404 error?

**Comment by jasminediaconu** [comment]
Hi @joe-re thanks for the reply, I get a different error on localhost:3000![image](https://user-images.githubusercontent.com/28813718/135576008-6b40048d-bf01-473d-a971-c83ca2cd4d05.jpeg)

**Comment by joe-re** [comment]
@jasminediaconu Hi, I've fixed some issues for dev docker. Please update your local repo to the latest and try it again.
If problem's persistent, please feel free to reopen this issue. Thanks.
