### ISSUE TITLE
Message sent without Content-Length header

### ISSUE THREAD

**Issue by QuadeMorrison** [joe-re/sql-language-server#9]
https://github.com/joe-re/sql-language-server/blob/3ba1d15c603b0a6e555be28a3fb7bee2e819c647/packages/server/bin/cli.ts#L24

It seems the protocol expects that messages are sent with the Content-Length header. Because this message is sent without it, it has prevented me from using a client (coc-nvim) with this language server, which expects to receive the above header with every message.

**Comment by joe-re** [comment]
@QuadeMorrison I haven't used coc-nvim but have you got any error messages?

**Comment by CGNonofr** [comment]
Same issue, and another one in complete.ts:

`console.log(JSON.stringify(candidates))`

**Comment by mattn** [comment]
You can use workarround for this. Add below's line into first line of ~/.npm/bin/sql-language-server.

```
console.log = function() {}
```

**Comment by mattn** [comment]
ping @joe-re 

Currently, `--method stdin` always stop initialize. Can you fix this?

**Comment by joe-re** [comment]
@mattn ok, I'll look into it. Thank your for your reporting.

**Comment by joe-re** [comment]
@mattn released fixed version, please try it with latest one. thanks.

**Comment by mattn** [comment]
Works fine. Thank you.
