### ISSUE TITLE
Use pg_query for parsing instead of peg.js

### ISSUE THREAD

**Issue by wesselvdv** [joe-re/sql-language-server#97]
Have you ever heard/seen/read of [pg_query (2.0)](https://pganalyze.com/blog/pg-query-2-0-postgres-query-parser)? There’s a npm module ([psql-parser](https://github.com/pyramation/pgsql-parser)) that allows it to be used, and it might be a good fit instead of the parser generated by peg.js this library uses.

I would think that it would allow for more easier support of certain statements, and maybe procedures/functions/routines.

It's not a typescript lib, so the typings are a bit missing, but I found this [gist](https://gist.github.com/beeing/9f7ca576bb344cc772b18c825ec3eab6) that's at least defined a good amount already. From the looks of it, it should at least provide similar if not more functionality than the parser currently used. (`CTE aka WITH` for example)

**Comment by joe-re** [comment]
@wesselvdv Thanks for your suggestion.
Actually, I've thought about some existing parsing library though, there's some requirements for a parser.
I'm not familiar with pg_query and don't know it provides it or not yet though, let me explain the biggest one.
If you're familiar with it and have some information to resolve this, please share us!

It should return parsing results even if it's given incomplete SQL.
It needs to get completion. eg. When it parses `select * fro`, if the cursor on the last char, completion result should include  `FROM` keyword.
But most of parsers are failed to parse this kinda incomplete sentences and we can't get any information from it.
  [sqlparse](https://github.com/andialbrecht/sqlparse) which is well-known as used some of projects provide completion such as redash and mycli says `non-validating parser` themself. 
Actually, pegjs is not a non-validating parser though, we can build any parsing rules and include any information on parsing errors. Right now we've resolved this problem by this though, I'm afraid if it's a third-party library, it can be difficult.

**Comment by wesselvdv** [comment]
@joe-re I clearly lack the experience/knowledge for building an language server implementation, so thanks for the pointers. I have been looking for a viable DataGrip alternative for a while, and the biggest show stoppers are a missing prettifier and lsp implementation that can provide (`tables`, `columns`, `procedures`, `functions`, `types`, `schemas`, `domains`, etc.) Most I can find only support `tables`, and `columns` and are badly maintained. Hence my interest in this one, and my suggestion for pg_query. As that would've been my starting point if I wanted to build one myself.

> It should return parsing results even if it's given incomplete SQL. It needs to get completion. eg. When it parses `select * fro`, if the cursor on the last char, completion result should include `FROM` keyword. But most of parsers are failed to parse this kinda incomplete sentences and we can't get any information from it. 

I am not sure if I follow you correctly, but I think you're referring to the fact that it shouldn't error and still always return an optional property called `from`?

I forked your repo and monkey-patched `sql-parser` to a typescript project, and I installed `pgsql-parser` to run them side by side using your extremely useful included editor. For the example you gave (`SELECT * FRO`) I am getting the following results:

**peg.js**
```json
{
  "ast": {
    "type": "select",
    "keyword": {
      "type": "keyword",
      "value": "SELECT",
      "location": {
        "start": {
          "offset": 0,
          "line": 1,
          "column": 1
        },
        "end": {
          "offset": 6,
          "line": 1,
          "column": 7
        }
      }
    },
    "distinct": null,
    "columns": {
      "type": "star",
      "value": "*"
    },
    "from": null,
    "where": null,
    "groupby": null,
    "orderby": null,
    "limit": null,
    "location": {
      "start": {
        "offset": 0,
        "line": 1,
        "column": 1
      },
      "end": {
        "offset": 11,
        "line": 3,
        "column": 1
      }
    }
  },
  "param": []
}
```

**pgsql-parser**
```json
[
  {
    "RawStmt": {
      "stmt": {
        "SelectStmt": {
          "targetList": [
            {
              "ResTarget": {
                "val": {
                  "ColumnRef": {
                    "fields": [
                      {
                        "A_Star": {}
                      }
                    ],
                    "location": 9
                  }
                },
                "location": 9
              }
            }
          ],
          "limitOption": "LIMIT_OPTION_DEFAULT",
          "op": "SETOP_NONE"
        }
      }
    }
  }
]
```

Apart from the obvious different data structure, it does seem to return the exact same (lack) of information?

EDIT:

Having dug into the subject at hand a bit more, I think that this output from pgsql-parser it not sufficient atm. It’s missing some location information, and it won’t parse comments. I found this [issue](https://github.com/pyramation/libpg-query-node/issues/8) where they’re discussing exposing the libpg_query scanner in libpg-query. Seems that it would be extremely useful if this scanner/lexer would be available. As it provides all the tokens that are valid.

**Comment by joe-re** [comment]
@wesselvdv
> I am getting the following results:

I've tried to parse `SELECT * FRO` and got the below error.

```
SyntaxError: Expected "--", "/*", ";", "FROM", "GROUP", "LIMIT", "ORDER", "UNION", "WHERE", [ \t\n\r], or end of input but "F" found.
    at peg$buildStructuredError (/Users/noguchimasato/src/sql-language-server/packages/sql-parser/base/parser.js:1218:12)
    at Object.peg$parse [as parse] (/Users/noguchimasato/src/sql-language-server/packages/sql-parser/base/parser.js:10899:11)
    at Object.exports.parse (/Users/noguchimasato/src/sql-language-server/packages/sql-parser/index.js:7:19)
    at Object.<anonymous> (/Users/noguchimasato/src/sql-language-server/packages/sql-parser/test.ts:5:18)
    at Module._compile (node:internal/modules/cjs/loader:1095:14)
    at Module.m._compile (/Users/noguchimasato/.config/yarn/global/node_modules/ts-node/src/index.ts:1056:23)
    at Module._extensions..js (node:internal/modules/cjs/loader:1147:10)
    at Object.require.extensions.<computed> [as .ts] (/Users/noguchimasato/.config/yarn/global/node_modules/ts-node/src/index.ts:1059:12)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
```

It says the token at the cursor should be any of "FROM", "GROUP", "LIMIT", "ORDER", "UNION", "WHERE".
Actually, that is the completion way right now we're using, it includes "FROM" keyword and the token "FRO", then we can narrow down to "FROM" keyword from candidates.
Probably you parsed only "SELECT \*" part, I guess. We cut down after cursor parts on SQL sentence to get completion result, so even if you have "SELECT * FRO" sentense, if your cursor is on "*" token, the target would be "SELECT *".

> Having dug into the subject at hand a bit more, I think that this output from pgsql-parser it not sufficient atm. It’s missing some location information, and it won’t parse comments. 

I see. it's unfortunate.
I'm always considering adopting something third party parser, if it matches our usecase. Because to maintain parser is hard and if we can focus on only for editor Intellisense part, that would be great for letting our development speed be fast.
Let's keep in watch and if you have any information for it, please feel free to share us. Thanks!

**Comment by wesselvdv** [comment]
> 
> > I am getting the following results:
> 
> I've tried to parse `SELECT * FRO` and got the below error.
> 
> ```
> SyntaxError: Expected "--", "/*", ";", "FROM", "GROUP", "LIMIT", "ORDER", "UNION", "WHERE", [ \t\n\r], or end of input but "F" found.
>     at peg$buildStructuredError (/Users/noguchimasato/src/sql-language-server/packages/sql-parser/base/parser.js:1218:12)
>     at Object.peg$parse [as parse] (/Users/noguchimasato/src/sql-language-server/packages/sql-parser/base/parser.js:10899:11)
>     at Object.exports.parse (/Users/noguchimasato/src/sql-language-server/packages/sql-parser/index.js:7:19)
>     at Object.<anonymous> (/Users/noguchimasato/src/sql-language-server/packages/sql-parser/test.ts:5:18)
>     at Module._compile (node:internal/modules/cjs/loader:1095:14)
>     at Module.m._compile (/Users/noguchimasato/.config/yarn/global/node_modules/ts-node/src/index.ts:1056:23)
>     at Module._extensions..js (node:internal/modules/cjs/loader:1147:10)
>     at Object.require.extensions.<computed> [as .ts] (/Users/noguchimasato/.config/yarn/global/node_modules/ts-node/src/index.ts:1059:12)
>     at Module.load (node:internal/modules/cjs/loader:975:32)
>     at Function.Module._load (node:internal/modules/cjs/loader:822:12)
> ```
> 
> It says the token at the cursor should be any of "FROM", "GROUP", "LIMIT", "ORDER", "UNION", "WHERE". Actually, that is the completion way right now we're using, it includes "FROM" keyword and the token "FRO", then we can narrow down to "FROM" keyword from candidates. Probably you parsed only "SELECT *" part, I guess. We cut down after cursor parts on SQL sentence to get completion result, so even if you have "SELECT * FRO" sentense, if your cursor is on "*" token, the target would be "SELECT *".
> 

Alright, I see what I did wrong there. I monkey patched the sql-parser directly, and I was indeed only getting `SELECT *` instead of `SELECT * FRO`. When running the `SELECT * FRO` into `libpg-query` I get the following:

```
[Error: syntax error at or near "FRO"] {
   fileName: 'scan.l',
   functionName: 'scanner_yyerror',
   lineNumber: 1234,
   cursorPosition: 10,
   context: null
}
```

Which is in line with what you're saying, you'd like to see the possible keywords it could be instead of just a syntax error.

**Comment by joe-re** [comment]
@wesselvdv 
Thanks for your info!

> Which is in line with what you're saying, you'd like to see the possible keywords it could be instead of just a syntax error.

Yes, that's why right now we have our own parser.. I'll close it for now though, please let us know if you have any information for a great parser or solution, thanks. 🙏
